#
# docker compose up -d
#
version: "3"

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    dns:
      - 192.168.1.10
      - 208.67.222.222
    ports:
      - 8123:8123
    privileged: true
    volumes:
      - /home/pi/docker_config/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/docker_config/nginx-pm/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
  nginx-pm:
    container_name: nginx-pm
    image: 'jc21/nginx-proxy-manager:latest'
    # environment:
      # Uncomment this if you want to change the location of 
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    ports:
      # These ports are in format <host-port>:<container-port>
      - 80:80 # Public HTTP Port
      - 443:443 # Public HTTPS Port
      - 81:81 # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    volumes:
      - /home/pi/docker_config/nginx-pm/data:/data
      - /home/pi/docker_config/nginx-pm/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns:
      - 208.67.222.222
      - 208.67.220.220
    environment:
      FTLCONF_LOCAL_IPV4: "192.168.1.10"
      TZ: "Europe/London"
      WEBPASSWORD: "Nope"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8080:80/tcp
    volumes:
      - "/home/pi/docker_config/pihole/etc-pihole/:/etc/pihole/"
      - "/home/pi/docker_config/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    restart: unless-stopped
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    dns:
      - 192.168.1.10
      - 208.67.222.222
    environment:
      PGID: "1000"
      PUID: "1000"
      PLEX_CLAIM: "claim-6XFLkWDbjDw8qnuPiTme"
      TZ: "Europe/London"
      VERSION: "docker"
    ports:
      - 32400:32400
      - 1901:1900/udp # tweaked
      - 3005:3005
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - /home/pi/docker_config/plex/:/config
      - /mnt/mydisk/Transcode:/transcode
      - /mnt/mydisk/Media/Movies:/movies
      - /mnt/mydisk/Media/TV:/tv
    restart: unless-stopped
  samba:
    container_name: samba
    image: dperson/samba:latest
    environment:
      GROUPID: "65534"
      RECYCLE: "no"
      SHARE1: "backups;/mnt/mydisk/Backups;yes;no;yes;all;none;;Backups"
      SHARE2: "media;/mnt/mydisk/Media;yes;no;yes;all;none;;Media"
      TZ: "Europe/London"
      USERID: "65534"
      WORKGROUP: "WORKGROUP"
    ports:
      - 139:139
      - 445:445
    volumes:
      - /mnt/mydisk/Backups:/mnt/mydisk/Backups
      - /mnt/mydisk/Media:/mnt/mydisk/Media
    restart: unless-stopped
networks:
  default:
    external: true
    name: pi
