#
# docker compose up -d
#
version: "3"
services:
  openhab:
    container_name: openhab
    image: "openhab/openhab:latest"
    restart: unless-stopped
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/home/pi/docker_config/openhab/addons:/openhab/addons"
      - "/home/pi/docker_config/openhab/conf:/openhab/conf"
      - "/home/pi/docker_config/openhab/userdata:/openhab/userdata"
    environment:
      USER_ID: "1000"
      GROUP_ID: "1000"
      CRYPTO_POLICY: "unlimited"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/London"
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns:
      - 208.67.222.222
      - 208.67.220.220
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    environment:
      FTLCONF_LOCAL_IPV4: "192.168.1.10"
      TZ: "Europe/London"
      WEBPASSWORD: "NopeNopeNope"
    network_mode: host
    volumes:
      - "/home/pi/docker_config/pihole/etc-pihole/:/etc/pihole/"
      - "/home/pi/docker_config/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      PGID: "1000"
      PUID: "1000"
      PLEX_CLAIM: "claim-9tUqHoq4Gsjxb-CP85Yj"
      TZ: "Europe/London"
      VERSION: "docker"
    volumes:
      - /home/pi/docker_config/plex/:/config
      - /mnt/mydisk/Transcode:/transcode
      - /mnt/mydisk/Media/Movies:/movies
      - /mnt/mydisk/Media/TV:/tv
    restart: unless-stopped
  samba:
    image: dperson/samba:latest
    container_name: samba
    ports:
      - 139:139
      - 445:445
    environment:
      GROUPID: "65534"
      RECYCLE: "no"
      SHARE1: "backups;/mnt/mydisk/Backups;yes;no;yes;all;none;;Backups"
      SHARE2: "media;/mnt/mydisk/Media;yes;no;yes;all;none;;Media"
      TZ: "Europe/London"
      USERID: "65534"
      WORKGROUP: "WORKGROUP"
    volumes:
      - /mnt/mydisk/Backups:/mnt/mydisk/Backups
      - /mnt/mydisk/Media:/mnt/mydisk/Media
    restart: unless-stopped
