#
# docker compose up -d
#
# version: "3"

services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:latest"
    dns:
      - 192.168.1.10
      - 208.67.222.222
    ports:
      - 8123:8123
    privileged: true
    volumes:
      - /home/pi/docker_config/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/docker_config/nginx-pm/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
  ##minecraft:
    ##container_name: minecraft
    ##image: itzg/minecraft-bedrock-server:latest
    ##dns:
      ##- 192.168.1.10
      ##- 208.67.222.222
    ##environment:
      ##DIFFICULTY: normal
      ##EULA: "TRUE"
      ##GAMEMODE: survival
      ##SERVER_NAME: "Daddy's minecraft server"
      ##TZ: "Europe/London"
      ##VERSION: LATEST
    ##ports:
      ##- 19132:19132/udp
    ##volumes:
      ##- /home/pi/docker_config/minecraft/data:/data
    ##restart: unless-stopped
  nginx-pm:
    container_name: nginx-pm
    image: 'jc21/nginx-proxy-manager:latest'
    dns:
      - 192.168.1.10
      - 208.67.222.222
    ports:
      # These ports are in format <host-port>:<container-port>
      - 80:80 # Public HTTP Port
      - 443:443 # Public HTTPS Port
      - 81:81 # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    volumes:
      - /home/pi/docker_config/nginx-pm/data:/data
      - /home/pi/docker_config/nginx-pm/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns:
      - 208.67.222.222
      - 208.67.220.220
    environment:
      FTLCONF_LOCAL_IPV4: "192.168.1.10"
      TZ: "Europe/London"
      WEBPASSWORD: "N0Pe"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8080:80/tcp
    volumes:
      - "/home/pi/docker_config/pihole/etc-pihole/:/etc/pihole/"
      - "/home/pi/docker_config/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    restart: unless-stopped
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    dns:
      - 192.168.1.10
      - 208.67.222.222
    environment:
      PGID: "1000"
      PUID: "1000"
      PLEX_CLAIM: "claim-UuHeAvmwxZ1i6JSoWS3_"
      TZ: "Europe/London"
      VERSION: "docker"
    ports:
      - 32400:32400
      - 1901:1900/udp # tweaked
      - 3005:3005
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - /home/pi/docker_config/plex/:/config
      - /mnt/mydisk/Transcode:/transcode
      - /mnt/mydisk/Media/Movies:/movies
      - /mnt/mydisk/Media/TV:/tv
    restart: unless-stopped
  samba:
    container_name: samba
    image: dperson/samba:latest
    environment:
      GROUPID: "65534"
      RECYCLE: "no"
      SHARE1: "backups;/mnt/mydisk/Backups;yes;no;yes;all;none;;Backups"
      SHARE2: "media;/mnt/mydisk/Media;yes;no;yes;all;none;;Media"
      TZ: "Europe/London"
      USERID: "65534"
      WORKGROUP: "WORKGROUP"
    ports:
      - 139:139
      - 445:445
    volumes:
      - /mnt/mydisk/Backups:/mnt/mydisk/Backups
      - /mnt/mydisk/Media:/mnt/mydisk/Media
    restart: unless-stopped
  ##step-ca:
    ##container_name: step-ca
    ##image: "smallstep/step-ca:latest"
    ##dns:
      ##- 192.168.1.10
      ##- 208.67.222.222
    ##environment:
      ##DOCKER_STEPCA_INIT_NAME: "Zen CA"
      ##DOCKER_STEPCA_INIT_DNS_NAMES: "192.168.1.10,mercury,localhost"
      ##DOCKER_STEPCA_INIT_PASSWORD_FILE: "/home/step/secrets/password"
      ##DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT: "true"
    ##ports:
      ##- 9000:9000
    ##volumes:
      ##- /home/pi/docker_config/step-ca:/home/step
    ##restart: unless-stopped
networks:
  default:
    external: true
    name: pi
